services:
  web-centinela:
    container_name: web-centinela
    build:
      context: ./
      dockerfile: dev/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    networks:
      - centinela-network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.local

networks:
  centinela-network:
    driver: bridge
